### ISSUE TITLE
Error 500 and Error Undefined index

### ISSUE THREAD

**Issue by poblabs** [robinp7720/Blue-Stats-Minecraft#61]
I'm continuing to troubleshoot my problems outlined here: https://github.com/robinp7720/Blue-Stats-Minecraft/issues/39#issuecomment-251203986

I turned debugging on, and I still have 0 page styles, however when I access a player page, I am getting `Undefined index` errors. 

Any thoughts?

```

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Notice: Undefined index: value in /var/www/html/redacted/statstest/classes/player.class.php on line 56

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in /var/www/html/redacted/statstest/functions/utils.func.php:5 Stack trace: #0 /var/www/html/redacted/statstest/functions/utils.func.php(5): DateTime->__construct('@0') #1 /var/www/html/redacted/statstest/plugins/lolmewnStats/core.php(150): secondsToTime(16302) #2 /var/www/html/redacted/statstest/classes/player.class.php(54): lolmewnStats->getStat('last_join', 'f5503099-1ad3-4...') #3 /var/www/html/redacted/statstest/classes/view.class.php(51): player->renderPlayerAllStats() #4 /var/www/html/redacted/statstest/classes/view.class.php(109): view->render('page') #5 in /var/www/html/redacted/statstest/functions/utils.func.php on line 5
```

**Comment by robinp7720** [comment]
Fixed in latest commits
