### ISSUE TITLE
Stats v3.1.1-RC generated an exception while executing task 3

### ISSUE THREAD

**Issue by KayzerCode** [robinp7720/Blue-Stats-Minecraft#71]
Please, help me to understand the reason of this errors:

`[10:38:30 WARN]: [Stats] Plugin Stats v3.1.1-RC generated an exception while executing task 3
java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_121]
        at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_121]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:239) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.Gson.toJson(Gson.java:593) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.Gson.toJson(Gson.java:572) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.Gson.toJson(Gson.java:527) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at com.google.gson.Gson.toJson(Gson.java:507) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at nl.lolmewn.stats.storage.FlatfileStorageEngine.save(FlatfileStorageEngine.java:88) ~[?:?]
        at nl.lolmewn.stats.user.StatsUserManager.saveUser(StatsUserManager.java:36) ~[?:?]
        at nl.lolmewn.stats.bukkit.BukkitMain.lambda$null$2(BukkitMain.java:281) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_121]
        at nl.lolmewn.stats.bukkit.BukkitMain.lambda$scheduleDataSaver$3(BukkitMain.java:279) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

**Comment by robinp7720** [comment]
This is not the place to submit errors/bugs about lolmewnstats
